# Generated by Django 2.2.12 on 2021-01-22 19:46

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MolecularData',
            fields=[
                ('db_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('casNo', models.TextField()),
                ('name', models.TextField()),
                ('formula', models.TextField()),
            ],
        ),
    ]
