# Generated by Django 2.2.12 on 2021-02-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210123_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('casNo', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reagentpropertydata',
            name='name',
        ),
    ]
