# Generated by Django 2.2.12 on 2021-02-12 08:10

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210212_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False),
        ),
    ]
