# Generated by Django 2.2.12 on 2021-06-07 03:04

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('history', models.TextField()),
            ],
        ),
    ]
